import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className="flex gap-4"
      >
    <SidebarProvider>
      <AppSidebar />
      <main className="w-full">
        <SidebarTrigger />
        <div className="px-12 py-4">
          {children}
        </div>
      </main>
    </SidebarProvider>
      </body>
    </html>
  );
}
